default_context:
  full_name: "Brookhaven National Laboratory"
  email: "mrakitin@bnl.gov"
  github_username: "NSLS-II"
  project_name: "blop"
  package_dist_name: "blop"
  package_dir_name: "blop"
  repo_name: "blop"
  project_short_description: "Beamline Optimization Tools"
  minimum_supported_python_version: "3.8"
replay_dir: "~/tmp/new-repo"
