expected_improvement:
  pretty_name: Expected improvement
  description: The expected value of max(f(x) - \nu, 0), where \nu is the current maximum.
  identifiers:
  - ei
  multitask_only: false
  type: analytic

monte_carlo_expected_improvement:
  description: The expected value of max(f(x) - \nu, 0), where \nu is the current maximum.
  identifiers:
  - qei
  multitask_only: false
  pretty_name: Monte Carlo Expected improvement
  type: monte_carlo

expected_mean:
  description: The expected value at each input.
  identifiers:
  - em
  multitask_only: false
  pretty_name: Expected mean
  type: analytic

monte_carlo_expected_mean:
  description: The expected value at each input.
  identifiers:
  - qem
  multitask_only: false
  pretty_name: Monte Carlo expected mean
  type: monte_carlo

lower_bound_max_value_entropy:
  description: Max entropy search, basically
  identifiers:
  - lbmve
  - lbmes
  - gibbon
  multitask_only: false
  pretty_name: Lower bound max value entropy
  type: monte_carlo

noisy_expected_hypervolume_improvement:
  description: It's like a big box. How big is the box?
  identifiers:
  - nehvi
  multitask_only: true
  pretty_name: Noisy expected hypervolume improvement
  type: analytic

probability_of_improvement:
  description: The probability that this input improves on the current maximum.
  identifiers:
  - pi
  multitask_only: false
  pretty_name: Probability of improvement
  type: analytic

monte_carlo_probability_of_improvement:
  description: The probability that this input improves on the current maximum.
  identifiers:
  - qpi
  multitask_only: false
  pretty_name: Monte Carlo probability of improvement
  type: monte_carlo

random:
  description: Uniformly-sampled random points.
  identifiers:
  - r
  multitask_only: false
  pretty_name: Random
  type: none

quasi-random:
  description: Sobol-sampled quasi-random points.
  identifiers:
  - qr
  multitask_only: false
  pretty_name: Quasi-random
  type: none

grid:
  description: A grid scan over the parameters.
  identifiers:
  - g
  - gs
  multitask_only: false
  pretty_name: Grid scan
  type: none

upper_confidence_bound:
  default_args:
    beta: 4
  description: The expected value, plus some multiple of the uncertainty (typically \mu + 2\sigma).
  identifiers:
  - ucb
  multitask_only: false
  pretty_name: Upper confidence bound
  type: analytic

monte_carlo_upper_confidence_bound:
  default_args:
    beta: 4
  description: The expected value, plus some multiple of the uncertainty (typically \mu + 2\sigma).
  identifiers:
  - qucb
  multitask_only: false
  pretty_name: Monte Carlo upper confidence bound
  type: monte_carlo
